# Generated by Django 5.0.6 on 2024-07-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pastebin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
